# Site wide configuration

title: Helga Ruppe
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Helga Ruppe
  avatar: 
  bio: Helga’s academic career began at Western many moons ago when she took an undergraduate degree in German Language and Literature, supplemented by Latin, Ancient Greek, and Old English.  She then went to Toronto to study at the Centre for Medieval Studies at the University of Toronto, where she earned an MA in Medieval Studies before life interfered.  In 2012, Helga returned to Western for a second undergraduate degree, this one in Visual Arts and Medieval Studies.  Fascinated by medieval gardens and botanical texts, Helga seeks to investigate how the perception of this lore manifests in contemporary medievalizing fantasy and historical novels, and what that tells us about modern society.
Helga lives with her husband, four children, and two cats—not to mention foxes, groundhogs, hares, and deer—in two acres of wilderness which she dreams of transforming into a medieval pleasure garden.

  email: HRuppe@UWO.ca
  # Do not include the @ symbol in your Twitter username
  twitter: HelgaRuppe
  linkedin: #username
  github: HelgaRuppe
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
  facebook: HelgaRuppe
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: #yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
